name: Verify External PR

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches:
      - dev

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: src/extension.yaml

      - name: Check extension version
        run: grep "version" src/extension.yaml

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dtextcli
        uses: ./.github/actions/dtextcli-setup

      - name: Build extension using dtextcli
        uses: ./.github/actions/build
